const actionNames = {
	ADD_FILTER: "ADD_FILTER",
	GET_PACKAGES: "GET_PACKAGES",
	REMOVE_FILTER: "REMOVE_FILTER",
	SET_PACKAGES: "SET_PACKAGES",
	SET_IS_UPLOADING: "SET_IS_UPLOADING",
	SET_USER_INFORMATION: "SET_USER_INFORMATION"
};

export default actionNames;
