const actionNames = {
	APPEND_TO_FILE_LIST: "APPEND_TO_FILE_LIST",
	CHANGE_UPLOAD_TAB: "CHANGE_UPLOAD_TAB",
	SET_UPLOADED_FILES_LIST: "SET_UPLOADED_FILES_LIST",
	SHOW_UPLOAD_MODAL: "SHOW_UPLOAD_MODAL",
	UPDATE_FILE_DESCRIPTION: "UPDATE_FILE_DESCRIPTION",
    UPDATE_FILES_TO_UPLOAD: "UPDATE_FILES_TO_UPLOAD",
    UPDATE_UPLOAD_RESPONSE: "UPDATE_UPLOAD_RESPONSE",
};

export default actionNames;